sonar.organization=jbcom
sonar.projectKey=jbcom_rpgjs-patches
sonar.projectName=rpgjs-patches
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,docs/**,examples/**
